export const RESERVED_SLUGS = [
  "login",
  "register",
  "forgot-password",
  "reset-password",
  "verify-email",
  "dashboard",
  "admin",
  "templates",
  "demo",
  "pricing",
  "faq",
  "blog",
  "inspiration",
  "contact",
  "api",
  "invitation",
  "_next",
  "images",
  "icons",
  "ornaments",
  "templates-assets",
  "uploads",
  "robots.txt",
  "sitemap.xml",
  "favicon.ico",
] as const;
